main: ink.anh.shop.AnhyShop
name: AnhyShop
version: 0.1.0
author: AnhyDev
api-version: 1.13
description: AnhyShop projekt
website: http://anh.ink
commands:
    shop:
        aliases: [anhyshop]
        usage: "[AnhyShop] The command '/shop (/anhyshop)' execution error, please check the arguments' correctness."