main: ink.anh.shop.AnhyShop
name: AnhyShop
version: 0.4.0
author: AnhyDev
api-version: 1.13
depend: [AnhyLibAPI]
softdepend: [AnhyLingo]
description: AnhyShop is a unique plugin for creating merchants and trading on Minecraft servers
website: http://anh.ink/anhyshop
commands:
    shop:
        aliases: [anhyshop]
        usage: "[AnhyShop] The command '/shop (/anhyshop)' execution error, please check the arguments' correctness."